version: '3'

services:
  nginx:
    build: docker/nginx
    ports:
      - 80:80
      - 8080:8080
    links:
      - app
    volumes:
      - ./:/var/www/rt-chat
  app:
    build: docker/app
    volumes:
      - ./:/var/www/rt-chat
    ports:
    - 9501:9501
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: chat
      POSTGRES_USER: chat
      POSTGRES_DB: chat
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
#  cron:
#    build: docker/cron
#    volumes:
#      - ./:/var/www/rt-chat
#    ports:
#    - 9501:9501
#    command: php artisan swoole:http start
#    depends_on:
#      - app
volumes:
  postgresdata:
