version: '3'

services:
  nginx:
    build: docker/nginx
    ports:
      - 80:80
      - 8080:8080
    links:
      - php
    volumes:
      - ./:/var/www/rt-chat
  php:
    build: docker/php
    volumes:
      - ./:/var/www/rt-chat
    ports:
    - 9501:9501
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: chat
      POSTGRES_USER: chat
      POSTGRES_DB: chat
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
